// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.8
// source: migrat.proto

package contact

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ModuleStart_ModuleType int32

const (
	ModuleStart_MODULE_SYSTEMSHELL ModuleStart_ModuleType = 0
	ModuleStart_MODULE_WASM        ModuleStart_ModuleType = 1
	ModuleStart_MODULE_PROCESS     ModuleStart_ModuleType = 2
)

// Enum value maps for ModuleStart_ModuleType.
var (
	ModuleStart_ModuleType_name = map[int32]string{
		0: "MODULE_SYSTEMSHELL",
		1: "MODULE_WASM",
		2: "MODULE_PROCESS",
	}
	ModuleStart_ModuleType_value = map[string]int32{
		"MODULE_SYSTEMSHELL": 0,
		"MODULE_WASM":        1,
		"MODULE_PROCESS":     2,
	}
)

func (x ModuleStart_ModuleType) Enum() *ModuleStart_ModuleType {
	p := new(ModuleStart_ModuleType)
	*p = x
	return p
}

func (x ModuleStart_ModuleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModuleStart_ModuleType) Descriptor() protoreflect.EnumDescriptor {
	return file_migrat_proto_enumTypes[0].Descriptor()
}

func (ModuleStart_ModuleType) Type() protoreflect.EnumType {
	return &file_migrat_proto_enumTypes[0]
}

func (x ModuleStart_ModuleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModuleStart_ModuleType.Descriptor instead.
func (ModuleStart_ModuleType) EnumDescriptor() ([]byte, []int) {
	return file_migrat_proto_rawDescGZIP(), []int{0, 0}
}

type ModuleStart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Args []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	Type ModuleStart_ModuleType `protobuf:"varint,4,opt,name=type,proto3,enum=migrat.ModuleStart_ModuleType" json:"type,omitempty"`
}

func (x *ModuleStart) Reset() {
	*x = ModuleStart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_migrat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModuleStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleStart) ProtoMessage() {}

func (x *ModuleStart) ProtoReflect() protoreflect.Message {
	mi := &file_migrat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleStart.ProtoReflect.Descriptor instead.
func (*ModuleStart) Descriptor() ([]byte, []int) {
	return file_migrat_proto_rawDescGZIP(), []int{0}
}

func (x *ModuleStart) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModuleStart) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ModuleStart) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ModuleStart) GetType() ModuleStart_ModuleType {
	if x != nil {
		return x.Type
	}
	return ModuleStart_MODULE_SYSTEMSHELL
}

type ModuleList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Modules []string `protobuf:"bytes,1,rep,name=modules,proto3" json:"modules,omitempty"`
}

func (x *ModuleList) Reset() {
	*x = ModuleList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_migrat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModuleList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleList) ProtoMessage() {}

func (x *ModuleList) ProtoReflect() protoreflect.Message {
	mi := &file_migrat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleList.ProtoReflect.Descriptor instead.
func (*ModuleList) Descriptor() ([]byte, []int) {
	return file_migrat_proto_rawDescGZIP(), []int{1}
}

func (x *ModuleList) GetModules() []string {
	if x != nil {
		return x.Modules
	}
	return nil
}

type ModuleOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Output string `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
}

func (x *ModuleOutput) Reset() {
	*x = ModuleOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_migrat_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModuleOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleOutput) ProtoMessage() {}

func (x *ModuleOutput) ProtoReflect() protoreflect.Message {
	mi := &file_migrat_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleOutput.ProtoReflect.Descriptor instead.
func (*ModuleOutput) Descriptor() ([]byte, []int) {
	return file_migrat_proto_rawDescGZIP(), []int{2}
}

func (x *ModuleOutput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModuleOutput) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type ModuleInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Input string `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
}

func (x *ModuleInput) Reset() {
	*x = ModuleInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_migrat_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModuleInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleInput) ProtoMessage() {}

func (x *ModuleInput) ProtoReflect() protoreflect.Message {
	mi := &file_migrat_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleInput.ProtoReflect.Descriptor instead.
func (*ModuleInput) Descriptor() ([]byte, []int) {
	return file_migrat_proto_rawDescGZIP(), []int{3}
}

func (x *ModuleInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModuleInput) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_migrat_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_migrat_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_migrat_proto_rawDescGZIP(), []int{4}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeepOpen bool `protobuf:"varint,1,opt,name=keep_open,json=keepOpen,proto3" json:"keep_open,omitempty"`
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_migrat_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_migrat_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_migrat_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatResponse) GetKeepOpen() bool {
	if x != nil {
		return x.KeepOpen
	}
	return false
}

type Ident struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CampainId    string `protobuf:"bytes,2,opt,name=campainId,proto3" json:"campainId,omitempty"`
	ComputerName string `protobuf:"bytes,3,opt,name=computerName,proto3" json:"computerName,omitempty"`
	Processname  string `protobuf:"bytes,4,opt,name=processname,proto3" json:"processname,omitempty"`
	Username     string `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *Ident) Reset() {
	*x = Ident{}
	if protoimpl.UnsafeEnabled {
		mi := &file_migrat_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ident) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ident) ProtoMessage() {}

func (x *Ident) ProtoReflect() protoreflect.Message {
	mi := &file_migrat_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ident.ProtoReflect.Descriptor instead.
func (*Ident) Descriptor() ([]byte, []int) {
	return file_migrat_proto_rawDescGZIP(), []int{6}
}

func (x *Ident) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Ident) GetCampainId() string {
	if x != nil {
		return x.CampainId
	}
	return ""
}

func (x *Ident) GetComputerName() string {
	if x != nil {
		return x.ComputerName
	}
	return ""
}

func (x *Ident) GetProcessname() string {
	if x != nil {
		return x.Processname
	}
	return ""
}

func (x *Ident) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type TakeScreenshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Screen int32 `protobuf:"varint,1,opt,name=screen,proto3" json:"screen,omitempty"`
}

func (x *TakeScreenshot) Reset() {
	*x = TakeScreenshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_migrat_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TakeScreenshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakeScreenshot) ProtoMessage() {}

func (x *TakeScreenshot) ProtoReflect() protoreflect.Message {
	mi := &file_migrat_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakeScreenshot.ProtoReflect.Descriptor instead.
func (*TakeScreenshot) Descriptor() ([]byte, []int) {
	return file_migrat_proto_rawDescGZIP(), []int{7}
}

func (x *TakeScreenshot) GetScreen() int32 {
	if x != nil {
		return x.Screen
	}
	return 0
}

type Screenshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time string `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Screenshot) Reset() {
	*x = Screenshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_migrat_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Screenshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Screenshot) ProtoMessage() {}

func (x *Screenshot) ProtoReflect() protoreflect.Message {
	mi := &file_migrat_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Screenshot.ProtoReflect.Descriptor instead.
func (*Screenshot) Descriptor() ([]byte, []int) {
	return file_migrat_proto_rawDescGZIP(), []int{8}
}

func (x *Screenshot) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *Screenshot) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_migrat_proto protoreflect.FileDescriptor

var file_migrat_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x6d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x22, 0xc8, 0x01, 0x0a, 0x0b, 0x4d, 0x6f, 0x64, 0x75, 0x6c,
	0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x12,
	0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72,
	0x67, 0x73, 0x12, 0x32, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x1e, 0x2e, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x2e, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x2e, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x49, 0x0a, 0x0a, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x12, 0x4d, 0x4f, 0x44, 0x55, 0x4c, 0x45, 0x5f, 0x53,
	0x59, 0x53, 0x54, 0x45, 0x4d, 0x53, 0x48, 0x45, 0x4c, 0x4c, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b,
	0x4d, 0x4f, 0x44, 0x55, 0x4c, 0x45, 0x5f, 0x57, 0x41, 0x53, 0x4d, 0x10, 0x01, 0x12, 0x12, 0x0a,
	0x0e, 0x4d, 0x4f, 0x44, 0x55, 0x4c, 0x45, 0x5f, 0x50, 0x52, 0x4f, 0x43, 0x45, 0x53, 0x53, 0x10,
	0x02, 0x22, 0x26, 0x0a, 0x0a, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x22, 0x3a, 0x0a, 0x0c, 0x4d, 0x6f, 0x64,
	0x75, 0x6c, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x37, 0x0a, 0x0b, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x49,
	0x6e, 0x70, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x22, 0x21,
	0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x30, 0x0a, 0x11, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6b, 0x65, 0x65, 0x70, 0x5f, 0x6f,
	0x70, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x6b, 0x65, 0x65, 0x70, 0x4f,
	0x70, 0x65, 0x6e, 0x22, 0x97, 0x01, 0x0a, 0x05, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x63, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x63, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x63,
	0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x28, 0x0a,
	0x0e, 0x54, 0x61, 0x6b, 0x65, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x73, 0x68, 0x6f, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x22, 0x34, 0x0a, 0x0a, 0x53, 0x63, 0x72, 0x65, 0x65,
	0x6e, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x03, 0x5a,
	0x01, 0x2e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_migrat_proto_rawDescOnce sync.Once
	file_migrat_proto_rawDescData = file_migrat_proto_rawDesc
)

func file_migrat_proto_rawDescGZIP() []byte {
	file_migrat_proto_rawDescOnce.Do(func() {
		file_migrat_proto_rawDescData = protoimpl.X.CompressGZIP(file_migrat_proto_rawDescData)
	})
	return file_migrat_proto_rawDescData
}

var file_migrat_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_migrat_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_migrat_proto_goTypes = []interface{}{
	(ModuleStart_ModuleType)(0), // 0: migrat.ModuleStart.ModuleType
	(*ModuleStart)(nil),         // 1: migrat.ModuleStart
	(*ModuleList)(nil),          // 2: migrat.ModuleList
	(*ModuleOutput)(nil),        // 3: migrat.ModuleOutput
	(*ModuleInput)(nil),         // 4: migrat.ModuleInput
	(*Error)(nil),               // 5: migrat.Error
	(*HeartbeatResponse)(nil),   // 6: migrat.HeartbeatResponse
	(*Ident)(nil),               // 7: migrat.Ident
	(*TakeScreenshot)(nil),      // 8: migrat.TakeScreenshot
	(*Screenshot)(nil),          // 9: migrat.Screenshot
}
var file_migrat_proto_depIdxs = []int32{
	0, // 0: migrat.ModuleStart.type:type_name -> migrat.ModuleStart.ModuleType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_migrat_proto_init() }
func file_migrat_proto_init() {
	if File_migrat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_migrat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModuleStart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_migrat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModuleList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_migrat_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModuleOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_migrat_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModuleInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_migrat_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_migrat_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartbeatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_migrat_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ident); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_migrat_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TakeScreenshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_migrat_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Screenshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_migrat_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_migrat_proto_goTypes,
		DependencyIndexes: file_migrat_proto_depIdxs,
		EnumInfos:         file_migrat_proto_enumTypes,
		MessageInfos:      file_migrat_proto_msgTypes,
	}.Build()
	File_migrat_proto = out.File
	file_migrat_proto_rawDesc = nil
	file_migrat_proto_goTypes = nil
	file_migrat_proto_depIdxs = nil
}
