[package]
name = "harvester-bin"
version = "0.1.0"
edition = "2021"

[lib]
name = "harvester"
path = "src/lib.rs"
crate-type =["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.197"
serde_json = "1.0.114"
